### ISSUE TITLE
Implement Normalization

### ISSUE THREAD

**Issue by lemire** [ada-url/idna#1]
We need to [normalize](https://www.unicode.org/reports/tr46/#ProcessingStepNormalize) the domain_name string to Unicode Normalization Form C. See  [Perl script that does it](https://dev.w3.org/cvsweb/charlint/charlint.pl?rev=1.28;content-type=text%2Fplain).

**Comment by anonrig** [comment]
Reference: https://unicode.org/reports/tr15/

**Comment by anonrig** [comment]
Example C++ implementation: https://github.com/ufal/unilib/blob/master/unilib/uninorms.h

**Comment by anonrig** [comment]
https://www.unicode.org/L2/L1999/UnicodeData.html

**Comment by lemire** [comment]
Solved by unilib.
