### ISSUE TITLE
We need to check validity criteria

### ISSUE THREAD

**Issue by lemire** [ada-url/idna#2]
We need to verify that the label meets the validity criteria in Section 4.1, [Validity Criteria](https://www.unicode.org/reports/tr46/#Validity_Criteria) for the input Processing choice (Nontransitional). If any of the validity criteria are not satisfied, record that there was an error.

**Comment by lemire** [comment]
@anonrig has implemented a skeleton.

**Comment by lemire** [comment]
@anonrig Are you able to finish the skeleton?

**Comment by anonrig** [comment]
Yes, I'm working on it, but I'm a little slow due to unexpected circumstances.
