### ISSUE TITLE
Implement to_unicode

### ISSUE THREAD

**Issue by lemire** [ada-url/idna#4]
It is just the reverse operation from to_ascii, seemingly without all the dense requirements.

**Comment by lemire** [comment]
@miguelteixeiraa This might be a doable task if you are interested.

**Comment by miguelteixeiraa** [comment]
I'll pick up this one!

**Comment by lemire** [comment]
We don't have the tests for it yet, but if you look at
https://github.com/ada-url/idna/blob/main/tests/to_ascii_tests.cpp

You should figure out quickly how to do the reverse.

**Comment by lemire** [comment]
@miguelteixeiraa We now pass our own tests, so it should make your life easier.
