### ISSUE TITLE
Unicode 15.1 failed test cases

### ISSUE THREAD

**Issue by anonrig** [ada-url/idna#47]
It seems we are still failing for the following tests @lemire even after updating to 15.1

```
  "toascii.window.js": {
    "fail": {
      "note": "Unicode 15.1",
      "expected": [
        "\uD87E\uDC68.com (using URL)",
        "\uD87E\uDC68.com (using URL.host)",
        "\uD87E\uDC68.com (using URL.hostname)"
      ]
    }
  },
```

**Comment by lemire** [comment]
I am not sure that we have a bug in this library... it might be something else. See https://github.com/ada-url/idna/pull/48
