### ISSUE TITLE
OSFF Scorecard is busted

### ISSUE THREAD

**Issue by lemire** [ada-url/idna#50]
Our [OSFF Scorecard](https://github.com/ada-url/idna/commit/d854a58e1669ed90f0d69f1199555f1ec26568f1) checker in CI is busted.

**Comment by anonrig** [comment]
cc @UlisesGascon can you help?

**Comment by UlisesGascon** [comment]
Seems like it was disabled time ago and the logs are not there `Error: The log was not found. It may have been deleted based on retention settings.`. But I can do a PR updating dependencies as see if the original problem was solved. WDYT?

**Comment by anonrig** [comment]
Sounds like a good plan! Appreciate the help @UlisesGascon

**Comment by UlisesGascon** [comment]
Seems to be working again :partying_face:

**Comment by anonrig** [comment]
Thank you @UlisesGascon
